### ISSUE TITLE
Some inaccurate parts

### ISSUE THREAD

**Issue by PointsCoder** [Thinklab-SJTU/Awesome-LLM4AD#1]
Hi,

Thanks for this nice survey. I briefly looked through this paper and found taxonomy  seems inaccurate:

1. GPT-Driver should be a fine-tuning approach instead of prompt engineering.
2. DriveGPT4 and LanguageMPC should focus on control instead of planning. 

![image](https://github.com/Thinklab-SJTU/Awesome-LLM4AD/assets/28640612/3ddb64db-e9e9-4b62-991f-33b13f4b5e69)

**Comment by jayyoung0802** [comment]
Thank you so much for your feedback. We've made changes to our repository, specifically altering the task type of GPT-Driver to "Fine-tuning Pre-trained Model." Additionally, we will be updating the paper in our upcoming V2 version by the end of this month.  I apologize for any inconvenience this may have caused you.

Regarding the topic of planning and control, it involves harnessing the reasoning abilities of large language models to execute planning tasks and subsequently generate control signals for vehicles, essentially accomplishing the same objective. To eliminate any potential confusion, we have decided to rename the task from "planning" to "planning/control."

Thanks again for your correction！
