### ISSUE TITLE
Looking for suggestions

### ISSUE THREAD

**Issue by HarryHsing** [Thinklab-SJTU/Awesome-LLM4AD#7]
Hi Zhenjie,

Thank you very much for this great survey!

I wonder if you have any recommendations for the papers in LLM for AD that have released code?

I found too many papers out here in this field that do not have any code which is annoying, so really appreciate it.

Best,
Harry

**Comment by jayyoung0802** [comment]
Hi Harry,
Due to the rapid development in this field, many papers are still in the submission phase, and their codes might not yet be open-sourced. We have marked the accepted papers in our repository(such as CVPR 2024, ICLR xxxx), where you can try to find code links.

**Comment by HarryHsing** [comment]
> Hi Harry, Due to the rapid development in this field, many papers are still in the submission phase, and their codes might not yet be open-sourced. We have marked the accepted papers in our repository(such as CVPR 2024, ICLR xxxx), where you can try to find code links.

Thanks!
